server:
  port: 5000

spring:
  cloud:
    gateway:
      routes:
        - id: api-hello
          uri: http://hello-docker:8080/
          predicates:
            - Path=/api-hello/**
          filters:
            - StripPrefix=1